Repository celte-team/celte-system, pull requests merged in 2024-12, with the labels that each got.

#80 Add pulsar-express WEB UI configuration
  automations/run
  pulsar/docker-compose.yaml
Labels: steaming system

#68 add project licence commons-clause
  LICENCE.md
Labels: documentation

#102 feat: add RPC service accessors for chunk and grape classes
  system/runtime/include/CelteChunk.hpp
  system/runtime/include/CelteGrape.hpp
Labels: system
